all:
	javac --module-path $(PATH_TO_FX) --add-modules javafx.controls HelloFX.java

run:
	java --module-path $(PATH_TO_FX) --add-modules javafx.controls HelloFX

run2:
	java -Dsun.java2d.uiScale=2.0 --module-path $(PATH_TO_FX) --add-modules javafx.controls HelloFX
